<a href="https://colab.research.google.com/github/daehkim/pair-trading/blob/master/Backtesting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CS7641 Machine Learning
*Application of Machine Learning in Pairs Trading*

In [37]:
import pandas as pd
import numpy as np
import os
import datetime
import matplotlib.pyplot as plt

## Generate the input data

### Price history

Price history will be about only one stock.

In [63]:
# Import training dataset
price_history = pd.read_csv("training_price_data.csv")
price_history.head(3)

   PERMNO  price_20070103  ...  price_20151230  price_20151231
0   10025           49.06  ...           77.22           77.15
1   10026           41.02  ...          119.25          116.67
2   10032           24.12  ...           35.46           34.92

[3 rows x 2267 columns]

In [64]:
# Filtering the table only for the one price history
filter_col = [col for col in price_history if col.startswith('price_')]
price_history = price_history[filter_col].head(1)
price_history.head(3)

   price_20070103  price_20070104  ...  price_20151230  price_20151231
0           49.06           50.34  ...           77.22           77.15

[1 rows x 2266 columns]


### Trade history

Check the trade history data in here.
We generated the random data for the backtesting function test.

In [65]:
np.random.seed(1)

# Generate the z-score for the function test
total_len = len(columns)
z_score_list = [0] * total_len

random_list = np.random.normal(0, 1, 2266)
acc_num = 0
for i in range(total_len):
    if i%20==0:
        acc_num /= 10
    acc_num += random_list[i]
    z_score_list[i] = acc_num

# Plot the z-score we generate for the test
"""
x = np.array([num for num in range(total_len)])
y = np.array(z_score_list)
plt.plot(x, y)
plt.show()
"""

# Generate the trade_history based on the z-score
# trade_history will have 4 rows, which are index buy/sell and inverse buy/sell.
index_buy_list = [0] * total_len
index_sell_list = [0] * total_len
inverse_buy_list = [0] * total_len
inverse_sell_list = [0] * total_len
total_index = 0
total_inverse = 0
buy_amount = 10

for i in range(total_len):
    if z_score_list[i] >= 2 and total_index == 0:
        index_buy_list[i] = buy_amount
        total_index += buy_amount
    elif z_score_list[i] <= 0.5 and total_index == buy_amount:
        index_sell_list[i] = buy_amount
        total_index -= buy_amount
    elif z_score_list[i] <= -2 and total_inverse == 0:
        inverse_buy_list[i] = buy_amount
        total_inverse += buy_amount
    elif z_score_list[i] >= -0.5 and total_inverse == buy_amount:
        inverse_sell_list[i] = buy_amount
        total_inverse -= buy_amount

# Make the columns list
columns = []
for i, comp in enumerate(filter_col):
    columns.append("trade" + comp[5:])

# Generate the dataFrame with buy/sell history
trade_history = pd.DataFrame(
    [index_buy_list,
    index_sell_list,
    inverse_buy_list,
    inverse_sell_list],
    index = pd.MultiIndex.from_tuples(
        [('index', 'buy'), ('index', 'sell'), ('inverse', 'buy'), 
         ('inverse', 'sell')]),
    columns = columns
)

trade_history.head(4)

              trade_20070103  trade_20070104  ...  trade_20151230  trade_20151231
index   buy                0               0  ...               0               0
        sell               0               0  ...               0               0
inverse buy                0               0  ...               0               0
        sell               0               0  ...               0               0

[4 rows x 2266 columns]

## Backtesting

We will calculate the final price based on the

In [74]:
class Backtesting():
    """
    Run the backtesting and track the total property history
    """

    def __init__(self, initial_money, commission):
        self.total_money = initial_money
        self.commission = commission
        self.trade_results = {}

    def calculate_trade_results(self, stock_name, price_history, trade_history):
        """
        Args:
            price_history [$]: 1xT Stock price's history.
            trade_history: 4xT Stock trade's history 
                (index buy/sell, inverse buy/sell).
            commission: Broker commission when we sell the stock.
        Return:
            property_history [$]: 1xT property history.
        """

        # Initialize the variable
        price_history = price_history.to_numpy()
        trade_history = trade_history.to_numpy()
        total_len = price_history.size
        property_history = np.zeros((total_len))
        index_holding = 0
        inverse_holding = 0

        # Calculate the property_history for everyday and record on 
        # property_history array
        for i in range(total_len):
            # Calculate the inverse
            if inverse_holding > 0:
                pass

            # Calculate the change

        


    def sum_trade_results(self, ):
        """
        Args: 
            self.trade_results
        """
        pass

bt = Backtesting(initial_money = 10000, commission = 0.002)
bt.trade_results["RANDOM1"] = \
    bt.calculate_trade_results("RANDOM1", price_history, trade_history)
bt.trade_results["RANDOM2"] = \
    bt.calculate_trade_reulsts("RANDOM2", price_history, trade_history)