In [4]:
import pandas as pd
import numpy as np
import os
import datetime

In [5]:
#import training dataset
trdt = pd.read_csv("training_data.csv")
print("\nNumber of stocks (rows):", len(trdt))
print("\nNumber of days (columns):", len(trdt.columns))

Number of stocks (rows): 2060

Number of days (columns): 3635

In [6]:
L=list(trdt.columns);L[2266:]
#Cutoff  at 2267

['price_20151231',
 'bm_2010-01',
 'bm_2010-02',
 'bm_2010-03',
 'bm_2010-04',
 'bm_2010-05',
 'bm_2010-06',
 'bm_2010-07',
 'bm_2010-08',
 'bm_2010-09',
 'bm_2010-10',
 'bm_2010-11',
 'bm_2010-12',
 'bm_2011-01',
 'bm_2011-02',
 'bm_2011-03',
 'bm_2011-04',
 'bm_2011-05',
 'bm_2011-06',
 'bm_2011-07',
 'bm_2011-08',
 'bm_2011-09',
 'bm_2011-10',
 'bm_2011-11',
 'bm_2011-12',
 'bm_2012-01',
 'bm_2012-02',
 'bm_2012-03',
 'bm_2012-04',
 'bm_2012-05',
 'bm_2012-06',
 'bm_2012-07',
 'bm_2012-08',
 'bm_2012-09',
 'bm_2012-10',
 'bm_2012-11',
 'bm_2012-12',
 'bm_2013-01',
 'bm_2013-02',
 'bm_2013-03',
 'bm_2013-04',
 'bm_2013-05',
 'bm_2013-06',
 'bm_2013-07',
 'bm_2013-08',
 'bm_2013-09',
 'bm_2013-10',
 'bm_2013-11',
 'bm_2013-12',
 'bm_2014-01',
 'bm_2014-02',
 'bm_2014-03',
 'bm_2014-04',
 'bm_2014-05',
 'bm_2014-06',
 'bm_2014-07',
 'bm_2014-08',
 'bm_2014-09',
 'bm_2014-10',
 'bm_2014-11',
 'bm_2014-12',
 'bm_2015-01',
 'bm_2015-02',
 'bm_2015-03',
 'bm_2015-04',
 'bm_2015-05',
 'bm_2015-06',
 'bm_2015-07',
 'bm_2015-08',
 'bm_2015-09',
 'bm_2015-10',
 'bm_2015-11',
 'bm_2015-12',
 'pe_exi_2010-01',
 'pe_exi_2010-02',
 'pe_exi_2010-03',
 'pe_exi_2010-04',
 'pe_exi_2010-05',
 'pe_exi_2010-06',
 'pe_exi_2010-07',
 'pe_exi_2010-08',
 'pe_exi_2010-09',
 'pe_exi_2010-10',
 'pe_exi_2010-11',
 'pe_exi_2010-12',
 'pe_exi_2011-01',
 'pe_exi_2011-02',
 'pe_exi_2011-03',
 'pe_exi_2011-04',
 'pe_exi_2011-05',
 'pe_exi_2011-06',
 'pe_exi_2011-07',
 'pe_exi_2011-08',
 'pe_exi_2011-09',
 'pe_exi_2011-10',
 'pe_exi_2011-11',
 'pe_exi_2011-12',
 'pe_exi_2012-01',
 'pe_exi_2012-02',
 'pe_exi_2012-03',
 'pe_exi_2012-04',
 'pe_exi_2012-05',
 'pe_exi_2012-06',
 'pe_exi_2012-07',
 'pe_exi_2012-08',
 'pe_exi_2012-09',
 'pe_exi_2012-10',
 'pe_exi_2012-11',
 'pe_exi_2012-12',
 'pe_exi_2013-01',
 'pe_exi_2013-02',
 'pe_exi_2013-03',
 'pe_exi_2013-04',
 'pe_exi_2013-05',
 'pe_exi_2013-06',
 'pe_exi_2013-07',
 'pe_exi_2013-08',
 'pe_exi_2013-09',
 'pe_exi_2013-10',
 'pe_exi_2013-11',
 'pe_exi_2013-12',
 'pe_exi_2014-01',
 'pe_exi_2014-02',
 'pe_exi_2014-03',
 'pe_exi_2014-04',
 'pe_exi_2014-05',
 'pe_exi_2014-06',
 'pe_exi_2014-07',
 'pe_exi_2014-08',
 'pe_exi_2014-09',
 'pe_exi_2014-10',
 'pe_exi_2014-11',
 'pe_exi_2014-12',
 'pe_exi_2015-01',
 'pe_exi_2015-02',
 'pe_exi_2015-03',
 'pe_exi_2015-04',
 'pe_exi_2015-05',
 'pe_exi_2015-06',
 'pe_exi_2015-07',
 'pe_exi_2015-08',
 'pe_exi_2015-09',
 'pe_exi_2015-10',
 'pe_exi_2015-11',
 'pe_exi_2015-12',
 'npm_2010-01',
 'npm_2010-02',
 'npm_2010-03',
 'npm_2010-04',
 'npm_2010-05',
 'npm_2010-06',
 'npm_2010-07',
 'npm_2010-08',
 'npm_2010-09',
 'npm_2010-10',
 'npm_2010-11',
 'npm_2010-12',
 'npm_2011-01',
 'npm_2011-02',
 'npm_2011-03',
 'npm_2011-04',
 'npm_2011-05',
 'npm_2011-06',
 'npm_2011-07',
 'npm_2011-08',
 'npm_2011-09',
 'npm_2011-10',
 'npm_2011-11',
 'npm_2011-12',
 'npm_2012-01',
 'npm_2012-02',
 'npm_2012-03',
 'npm_2012-04',
 'npm_2012-05',
 'npm_2012-06',
 'npm_2012-07',
 'npm_2012-08',
 'npm_2012-09',
 'npm_2012-10',
 'npm_2012-11',
 'npm_2012-12',
 'npm_2013-01',
 'npm_2013-02',
 'npm_2013-03',
 'npm_2013-04',
 'npm_2013-05',
 'npm_2013-06',
 'npm_2013-07',
 'npm_2013-08',
 'npm_2013-09',
 'npm_2013-10',
 'npm_2013-11',
 'npm_2013-12',
 'npm_2014-01',
 'npm_2014-02',
 'npm_2014-03',
 'npm_2014-04',
 'npm_2014-05',
 'npm_2014-06',
 'npm_2014-07',
 'npm_2014-08',
 'npm_2014-09',
 'npm_2014-10',
 'npm_2014-11',
 'npm_2014-12',
 'npm_2015-01',
 'npm_2015-02',
 'npm_2015-03',
 'npm_2015-04',
 'npm_2015-05',
 'npm_2015-06',
 'npm_2015-07',
 'npm_2015-08',
 'npm_2015-09',
 'npm_2015-10',
 'npm_2015-11',
 'npm_2015-12',
 'cfm_2010-01',
 'cfm_2010-02',
 'cfm_2010-03',
 'cfm_2010-04',
 'cfm_2010-05',
 'cfm_2010-06',
 'cfm_2010-07',
 'cfm_2010-08',
 'cfm_2010-09',
 'cfm_2010-10',
 'cfm_2010-11',
 'cfm_2010-12',
 'cfm_2011-01',
 'cfm_2011-02',
 'cfm_2011-03',
 'cfm_2011-04',
 'cfm_2011-05',
 'cfm_2011-06',
 'cfm_2011-07',
 'cfm_2011-08',
 'cfm_2011-09',
 'cfm_2011-10',
 'cfm_2011-11',
 'cfm_2011-12',
 'cfm_2012-01',
 'cfm_2012-02',
 'cfm_2012-03',
 'cfm_2012-04',
 'cfm_2012-05',
 'cfm_2012-06',
 'cfm_2012-07',
 'cfm_2012-08',
 'cfm_2012-09',
 'cfm_2012-10',
 'cfm_2012-11',
 'cfm_2012-12',
 'cfm_2013-01',
 'cfm_2013-02',
 'cfm_2013-03',
 'cfm_2013-04',
 'cfm_2013-05',
 'cfm_2013-06',
 'cfm_2013-07',
 'cfm_2013-08',
 'cfm_2013-09',
 'cfm_2013-10',
 'cfm_2013-11',
 'cfm_2013-12',
 'cfm_2014-01',
 'cfm_2014-02',
 'cfm_2014-03',
 'cfm_2014-04',
 'cfm_2014-05',
 'cfm_2014-06',
 'cfm_2014-07',
 'cfm_2014-08',
 'cfm_2014-09',
 'cfm_2014-10',
 'cfm_2014-11',
 'cfm_2014-12',
 'cfm_2015-01',
 'cfm_2015-02',
 'cfm_2015-03',
 'cfm_2015-04',
 'cfm_2015-05',
 'cfm_2015-06',
 'cfm_2015-07',
 'cfm_2015-08',
 'cfm_2015-09',
 'cfm_2015-10',
 'cfm_2015-11',
 'cfm_2015-12',
 'roa_2010-01',
 'roa_2010-02',
 'roa_2010-03',
 'roa_2010-04',
 'roa_2010-05',
 'roa_2010-06',
 'roa_2010-07',
 'roa_2010-08',
 'roa_2010-09',
 'roa_2010-10',
 'roa_2010-11',
 'roa_2010-12',
 'roa_2011-01',
 'roa_2011-02',
 'roa_2011-03',
 'roa_2011-04',
 'roa_2011-05',
 'roa_2011-06',
 'roa_2011-07',
 'roa_2011-08',
 'roa_2011-09',
 'roa_2011-10',
 'roa_2011-11',
 'roa_2011-12',
 'roa_2012-01',
 'roa_2012-02',
 'roa_2012-03',
 'roa_2012-04',
 'roa_2012-05',
 'roa_2012-06',
 'roa_2012-07',
 'roa_2012-08',
 'roa_2012-09',
 'roa_2012-10',
 'roa_2012-11',
 'roa_2012-12',
 'roa_2013-01',
 'roa_2013-02',
 'roa_2013-03',
 'roa_2013-04',
 'roa_2013-05',
 'roa_2013-06',
 'roa_2013-07',
 'roa_2013-08',
 'roa_2013-09',
 'roa_2013-10',
 'roa_2013-11',
 'roa_2013-12',
 'roa_2014-01',
 'roa_2014-02',
 'roa_2014-03',
 'roa_2014-04',
 'roa_2014-05',
 'roa_2014-06',
 'roa_2014-07',
 'roa_2014-08',
 'roa_2014-09',
 'roa_2014-10',
 'roa_2014-11',
 'roa_2014-12',
 'roa_2015-01',
 'roa_2015-02',
 'roa_2015-03',
 'roa_2015-04',
 'roa_2015-05',
 'roa_2015-06',
 'roa_2015-07',
 'roa_2015-08',
 'roa_2015-09',
 'roa_2015-10',
 'roa_2015-11',
 'roa_2015-12',
 'roe_2010-01',
 'roe_2010-02',
 'roe_2010-03',
 'roe_2010-04',
 'roe_2010-05',
 'roe_2010-06',
 'roe_2010-07',
 'roe_2010-08',
 'roe_2010-09',
 'roe_2010-10',
 'roe_2010-11',
 'roe_2010-12',
 'roe_2011-01',
 'roe_2011-02',
 'roe_2011-03',
 'roe_2011-04',
 'roe_2011-05',
 'roe_2011-06',
 'roe_2011-07',
 'roe_2011-08',
 'roe_2011-09',
 'roe_2011-10',
 'roe_2011-11',
 'roe_2011-12',
 'roe_2012-01',
 'roe_2012-02',
 'roe_2012-03',
 'roe_2012-04',
 'roe_2012-05',
 'roe_2012-06',
 'roe_2012-07',
 'roe_2012-08',
 'roe_2012-09',
 'roe_2012-10',
 'roe_2012-11',
 'roe_2012-12',
 'roe_2013-01',
 'roe_2013-02',
 'roe_2013-03',
 'roe_2013-04',
 'roe_2013-05',
 'roe_2013-06',
 'roe_2013-07',
 'roe_2013-08',
 'roe_2013-09',
 'roe_2013-10',
 'roe_2013-11',
 'roe_2013-12',
 'roe_2014-01',
 'roe_2014-02',
 'roe_2014-03',
 'roe_2014-04',
 'roe_2014-05',
 'roe_2014-06',
 'roe_2014-07',
 'roe_2014-08',
 'roe_2014-09',
 'roe_2014-10',
 'roe_2014-11',
 'roe_2014-12',
 'roe_2015-01',
 'roe_2015-02',
 'roe_2015-03',
 'roe_2015-04',
 'roe_2015-05',
 'roe_2015-06',
 'roe_2015-07',
 'roe_2015-08',
 'roe_2015-09',
 'roe_2015-10',
 'roe_2015-11',
 'roe_2015-12',
 'pretret_noa_2010-01',
 'pretret_noa_2010-02',
 'pretret_noa_2010-03',
 'pretret_noa_2010-04',
 'pretret_noa_2010-05',
 'pretret_noa_2010-06',
 'pretret_noa_2010-07',
 'pretret_noa_2010-08',
 'pretret_noa_2010-09',
 'pretret_noa_2010-10',
 'pretret_noa_2010-11',
 'pretret_noa_2010-12',
 'pretret_noa_2011-01',
 'pretret_noa_2011-02',
 'pretret_noa_2011-03',
 'pretret_noa_2011-04',
 'pretret_noa_2011-05',
 'pretret_noa_2011-06',
 'pretret_noa_2011-07',
 'pretret_noa_2011-08',
 'pretret_noa_2011-09',
 'pretret_noa_2011-10',
 'pretret_noa_2011-11',
 'pretret_noa_2011-12',
 'pretret_noa_2012-01',
 'pretret_noa_2012-02',
 'pretret_noa_2012-03',
 'pretret_noa_2012-04',
 'pretret_noa_2012-05',
 'pretret_noa_2012-06',
 'pretret_noa_2012-07',
 'pretret_noa_2012-08',
 'pretret_noa_2012-09',
 'pretret_noa_2012-10',
 'pretret_noa_2012-11',
 'pretret_noa_2012-12',
 'pretret_noa_2013-01',
 'pretret_noa_2013-02',
 'pretret_noa_2013-03',
 'pretret_noa_2013-04',
 'pretret_noa_2013-05',
 'pretret_noa_2013-06',
 'pretret_noa_2013-07',
 'pretret_noa_2013-08',
 'pretret_noa_2013-09',
 'pretret_noa_2013-10',
 'pretret_noa_2013-11',
 'pretret_noa_2013-12',
 'pretret_noa_2014-01',
 'pretret_noa_2014-02',
 'pretret_noa_2014-03',
 'pretret_noa_2014-04',
 'pretret_noa_2014-05',
 'pretret_noa_2014-06',
 'pretret_noa_2014-07',
 'pretret_noa_2014-08',
 'pretret_noa_2014-09',
 'pretret_noa_2014-10',
 'pretret_noa_2014-11',
 'pretret_noa_2014-12',
 'pretret_noa_2015-01',
 'pretret_noa_2015-02',
 'pretret_noa_2015-03',
 'pretret_noa_2015-04',
 'pretret_noa_2015-05',
 'pretret_noa_2015-06',
 'pretret_noa_2015-07',
 'pretret_noa_2015-08',
 'pretret_noa_2015-09',
 'pretret_noa_2015-10',
 'pretret_noa_2015-11',
 'pretret_noa_2015-12',
 'GProf_2010-01',
 'GProf_2010-02',
 'GProf_2010-03',
 'GProf_2010-04',
 'GProf_2010-05',
 'GProf_2010-06',
 'GProf_2010-07',
 'GProf_2010-08',
 'GProf_2010-09',
 'GProf_2010-10',
 'GProf_2010-11',
 'GProf_2010-12',
 'GProf_2011-01',
 'GProf_2011-02',
 'GProf_2011-03',
 'GProf_2011-04',
 'GProf_2011-05',
 'GProf_2011-06',
 'GProf_2011-07',
 'GProf_2011-08',
 'GProf_2011-09',
 'GProf_2011-10',
 'GProf_2011-11',
 'GProf_2011-12',
 'GProf_2012-01',
 'GProf_2012-02',
 'GProf_2012-03',
 'GProf_2012-04',
 'GProf_2012-05',
 'GProf_2012-06',
 'GProf_2012-07',
 'GProf_2012-08',
 'GProf_2012-09',
 'GProf_2012-10',
 'GProf_2012-11',
 'GProf_2012-12',
 'GProf_2013-01',
 'GProf_2013-02',
 'GProf_2013-03',
 'GProf_2013-04',
 'GProf_2013-05',
 'GProf_2013-06',
 'GProf_2013-07',
 'GProf_2013-08',
 'GProf_2013-09',
 'GProf_2013-10',
 'GProf_2013-11',
 'GProf_2013-12',
 'GProf_2014-01',
 'GProf_2014-02',
 'GProf_2014-03',
 'GProf_2014-04',
 'GProf_2014-05',
 'GProf_2014-06',
 'GProf_2014-07',
 'GProf_2014-08',
 'GProf_2014-09',
 'GProf_2014-10',
 'GProf_2014-11',
 'GProf_2014-12',
 'GProf_2015-01',
 'GProf_2015-02',
 'GProf_2015-03',
 'GProf_2015-04',
 'GProf_2015-05',
 'GProf_2015-06',
 'GProf_2015-07',
 'GProf_2015-08',
 'GProf_2015-09',
 'GProf_2015-10',
 'GProf_2015-11',
 'GProf_2015-12',
 'totdebt_invcap_2010-01',
 'totdebt_invcap_2010-02',
 'totdebt_invcap_2010-03',
 'totdebt_invcap_2010-04',
 'totdebt_invcap_2010-05',
 'totdebt_invcap_2010-06',
 'totdebt_invcap_2010-07',
 'totdebt_invcap_2010-08',
 'totdebt_invcap_2010-09',
 'totdebt_invcap_2010-10',
 'totdebt_invcap_2010-11',
 'totdebt_invcap_2010-12',
 'totdebt_invcap_2011-01',
 'totdebt_invcap_2011-02',
 'totdebt_invcap_2011-03',
 'totdebt_invcap_2011-04',
 'totdebt_invcap_2011-05',
 'totdebt_invcap_2011-06',
 'totdebt_invcap_2011-07',
 'totdebt_invcap_2011-08',
 'totdebt_invcap_2011-09',
 'totdebt_invcap_2011-10',
 'totdebt_invcap_2011-11',
 'totdebt_invcap_2011-12',
 'totdebt_invcap_2012-01',
 'totdebt_invcap_2012-02',
 'totdebt_invcap_2012-03',
 'totdebt_invcap_2012-04',
 'totdebt_invcap_2012-05',
 'totdebt_invcap_2012-06',
 'totdebt_invcap_2012-07',
 'totdebt_invcap_2012-08',
 'totdebt_invcap_2012-09',
 'totdebt_invcap_2012-10',
 'totdebt_invcap_2012-11',
 'totdebt_invcap_2012-12',
 'totdebt_invcap_2013-01',
 'totdebt_invcap_2013-02',
 'totdebt_invcap_2013-03',
 'totdebt_invcap_2013-04',
 'totdebt_invcap_2013-05',
 'totdebt_invcap_2013-06',
 'totdebt_invcap_2013-07',
 'totdebt_invcap_2013-08',
 'totdebt_invcap_2013-09',
 'totdebt_invcap_2013-10',
 'totdebt_invcap_2013-11',
 'totdebt_invcap_2013-12',
 'totdebt_invcap_2014-01',
 'totdebt_invcap_2014-02',
 'totdebt_invcap_2014-03',
 'totdebt_invcap_2014-04',
 'totdebt_invcap_2014-05',
 'totdebt_invcap_2014-06',
 'totdebt_invcap_2014-07',
 'totdebt_invcap_2014-08',
 'totdebt_invcap_2014-09',
 'totdebt_invcap_2014-10',
 'totdebt_invcap_2014-11',
 'totdebt_invcap_2014-12',
 'totdebt_invcap_2015-01',
 'totdebt_invcap_2015-02',
 'totdebt_invcap_2015-03',
 'totdebt_invcap_2015-04',
 'totdebt_invcap_2015-05',
 'totdebt_invcap_2015-06',
 'totdebt_invcap_2015-07',
 'totdebt_invcap_2015-08',
 'totdebt_invcap_2015-09',
 'totdebt_invcap_2015-10',
 'totdebt_invcap_2015-11',
 'totdebt_invcap_2015-12',
 'capital_ratio_2010-01',
 'capital_ratio_2010-02',
 'capital_ratio_2010-03',
 'capital_ratio_2010-04',
 'capital_ratio_2010-05',
 'capital_ratio_2010-06',
 'capital_ratio_2010-07',
 'capital_ratio_2010-08',
 'capital_ratio_2010-09',
 'capital_ratio_2010-10',
 'capital_ratio_2010-11',
 'capital_ratio_2010-12',
 'capital_ratio_2011-01',
 'capital_ratio_2011-02',
 'capital_ratio_2011-03',
 'capital_ratio_2011-04',
 'capital_ratio_2011-05',
 'capital_ratio_2011-06',
 'capital_ratio_2011-07',
 'capital_ratio_2011-08',
 'capital_ratio_2011-09',
 'capital_ratio_2011-10',
 'capital_ratio_2011-11',
 'capital_ratio_2011-12',
 'capital_ratio_2012-01',
 'capital_ratio_2012-02',
 'capital_ratio_2012-03',
 'capital_ratio_2012-04',
 'capital_ratio_2012-05',
 'capital_ratio_2012-06',
 'capital_ratio_2012-07',
 'capital_ratio_2012-08',
 'capital_ratio_2012-09',
 'capital_ratio_2012-10',
 'capital_ratio_2012-11',
 'capital_ratio_2012-12',
 'capital_ratio_2013-01',
 'capital_ratio_2013-02',
 'capital_ratio_2013-03',
 'capital_ratio_2013-04',
 'capital_ratio_2013-05',
 'capital_ratio_2013-06',
 'capital_ratio_2013-07',
 'capital_ratio_2013-08',
 'capital_ratio_2013-09',
 'capital_ratio_2013-10',
 'capital_ratio_2013-11',
 'capital_ratio_2013-12',
 'capital_ratio_2014-01',
 'capital_ratio_2014-02',
 'capital_ratio_2014-03',
 'capital_ratio_2014-04',
 'capital_ratio_2014-05',
 'capital_ratio_2014-06',
 'capital_ratio_2014-07',
 'capital_ratio_2014-08',
 'capital_ratio_2014-09',
 'capital_ratio_2014-10',
 'capital_ratio_2014-11',
 'capital_ratio_2014-12',
 'capital_ratio_2015-01',
 'capital_ratio_2015-02',
 'capital_ratio_2015-03',
 'capital_ratio_2015-04',
 'capital_ratio_2015-05',
 'capital_ratio_2015-06',
 'capital_ratio_2015-07',
 'capital_ratio_2015-08',
 'capital_ratio_2015-09',
 'capital_ratio_2015-10',
 'capital_ratio_2015-11',
 'capital_ratio_2015-12',
 'debt_ebitda_2010-01',
 'debt_ebitda_2010-02',
 'debt_ebitda_2010-03',
 'debt_ebitda_2010-04',
 'debt_ebitda_2010-05',
 'debt_ebitda_2010-06',
 'debt_ebitda_2010-07',
 'debt_ebitda_2010-08',
 'debt_ebitda_2010-09',
 'debt_ebitda_2010-10',
 'debt_ebitda_2010-11',
 'debt_ebitda_2010-12',
 'debt_ebitda_2011-01',
 'debt_ebitda_2011-02',
 'debt_ebitda_2011-03',
 'debt_ebitda_2011-04',
 'debt_ebitda_2011-05',
 'debt_ebitda_2011-06',
 'debt_ebitda_2011-07',
 'debt_ebitda_2011-08',
 'debt_ebitda_2011-09',
 'debt_ebitda_2011-10',
 'debt_ebitda_2011-11',
 'debt_ebitda_2011-12',
 'debt_ebitda_2012-01',
 'debt_ebitda_2012-02',
 'debt_ebitda_2012-03',
 'debt_ebitda_2012-04',
 'debt_ebitda_2012-05',
 'debt_ebitda_2012-06',
 'debt_ebitda_2012-07',
 'debt_ebitda_2012-08',
 'debt_ebitda_2012-09',
 'debt_ebitda_2012-10',
 'debt_ebitda_2012-11',
 'debt_ebitda_2012-12',
 'debt_ebitda_2013-01',
 'debt_ebitda_2013-02',
 'debt_ebitda_2013-03',
 'debt_ebitda_2013-04',
 'debt_ebitda_2013-05',
 'debt_ebitda_2013-06',
 'debt_ebitda_2013-07',
 'debt_ebitda_2013-08',
 'debt_ebitda_2013-09',
 'debt_ebitda_2013-10',
 'debt_ebitda_2013-11',
 'debt_ebitda_2013-12',
 'debt_ebitda_2014-01',
 'debt_ebitda_2014-02',
 'debt_ebitda_2014-03',
 'debt_ebitda_2014-04',
 'debt_ebitda_2014-05',
 'debt_ebitda_2014-06',
 'debt_ebitda_2014-07',
 'debt_ebitda_2014-08',
 'debt_ebitda_2014-09',
 'debt_ebitda_2014-10',
 'debt_ebitda_2014-11',
 'debt_ebitda_2014-12',
 'debt_ebitda_2015-01',
 'debt_ebitda_2015-02',
 'debt_ebitda_2015-03',
 'debt_ebitda_2015-04',
 'debt_ebitda_2015-05',
 'debt_ebitda_2015-06',
 'debt_ebitda_2015-07',
 'debt_ebitda_2015-08',
 'debt_ebitda_2015-09',
 'debt_ebitda_2015-10',
 'debt_ebitda_2015-11',
 'debt_ebitda_2015-12',
 'lt_debt_2010-01',
 'lt_debt_2010-02',
 'lt_debt_2010-03',
 'lt_debt_2010-04',
 'lt_debt_2010-05',
 'lt_debt_2010-06',
 'lt_debt_2010-07',
 'lt_debt_2010-08',
 'lt_debt_2010-09',
 'lt_debt_2010-10',
 'lt_debt_2010-11',
 'lt_debt_2010-12',
 'lt_debt_2011-01',
 'lt_debt_2011-02',
 'lt_debt_2011-03',
 'lt_debt_2011-04',
 'lt_debt_2011-05',
 'lt_debt_2011-06',
 'lt_debt_2011-07',
 'lt_debt_2011-08',
 'lt_debt_2011-09',
 'lt_debt_2011-10',
 'lt_debt_2011-11',
 'lt_debt_2011-12',
 'lt_debt_2012-01',
 'lt_debt_2012-02',
 'lt_debt_2012-03',
 'lt_debt_2012-04',
 'lt_debt_2012-05',
 'lt_debt_2012-06',
 'lt_debt_2012-07',
 'lt_debt_2012-08',
 'lt_debt_2012-09',
 'lt_debt_2012-10',
 'lt_debt_2012-11',
 'lt_debt_2012-12',
 'lt_debt_2013-01',
 'lt_debt_2013-02',
 'lt_debt_2013-03',
 'lt_debt_2013-04',
 'lt_debt_2013-05',
 'lt_debt_2013-06',
 'lt_debt_2013-07',
 'lt_debt_2013-08',
 'lt_debt_2013-09',
 'lt_debt_2013-10',
 'lt_debt_2013-11',
 'lt_debt_2013-12',
 'lt_debt_2014-01',
 'lt_debt_2014-02',
 'lt_debt_2014-03',
 'lt_debt_2014-04',
 'lt_debt_2014-05',
 'lt_debt_2014-06',
 'lt_debt_2014-07',
 'lt_debt_2014-08',
 'lt_debt_2014-09',
 'lt_debt_2014-10',
 'lt_debt_2014-11',
 'lt_debt_2014-12',
 'lt_debt_2015-01',
 'lt_debt_2015-02',
 'lt_debt_2015-03',
 'lt_debt_2015-04',
 'lt_debt_2015-05',
 'lt_debt_2015-06',
 'lt_debt_2015-07',
 'lt_debt_2015-08',
 'lt_debt_2015-09',
 'lt_debt_2015-10',
 'lt_debt_2015-11',
 'lt_debt_2015-12',
 'cash_debt_2010-01',
 'cash_debt_2010-02',
 'cash_debt_2010-03',
 'cash_debt_2010-04',
 'cash_debt_2010-05',
 'cash_debt_2010-06',
 'cash_debt_2010-07',
 'cash_debt_2010-08',
 'cash_debt_2010-09',
 'cash_debt_2010-10',
 'cash_debt_2010-11',
 'cash_debt_2010-12',
 'cash_debt_2011-01',
 'cash_debt_2011-02',
 'cash_debt_2011-03',
 'cash_debt_2011-04',
 'cash_debt_2011-05',
 'cash_debt_2011-06',
 'cash_debt_2011-07',
 'cash_debt_2011-08',
 'cash_debt_2011-09',
 'cash_debt_2011-10',
 'cash_debt_2011-11',
 'cash_debt_2011-12',
 'cash_debt_2012-01',
 'cash_debt_2012-02',
 'cash_debt_2012-03',
 'cash_debt_2012-04',
 'cash_debt_2012-05',
 'cash_debt_2012-06',
 'cash_debt_2012-07',
 'cash_debt_2012-08',
 'cash_debt_2012-09',
 'cash_debt_2012-10',
 'cash_debt_2012-11',
 'cash_debt_2012-12',
 'cash_debt_2013-01',
 'cash_debt_2013-02',
 'cash_debt_2013-03',
 'cash_debt_2013-04',
 'cash_debt_2013-05',
 'cash_debt_2013-06',
 'cash_debt_2013-07',
 'cash_debt_2013-08',
 'cash_debt_2013-09',
 'cash_debt_2013-10',
 'cash_debt_2013-11',
 'cash_debt_2013-12',
 'cash_debt_2014-01',
 'cash_debt_2014-02',
 'cash_debt_2014-03',
 'cash_debt_2014-04',
 'cash_debt_2014-05',
 'cash_debt_2014-06',
 'cash_debt_2014-07',
 'cash_debt_2014-08',
 'cash_debt_2014-09',
 'cash_debt_2014-10',
 'cash_debt_2014-11',
 'cash_debt_2014-12',
 'cash_debt_2015-01',
 'cash_debt_2015-02',
 'cash_debt_2015-03',
 'cash_debt_2015-04',
 'cash_debt_2015-05',
 'cash_debt_2015-06',
 'cash_debt_2015-07',
 'cash_debt_2015-08',
 'cash_debt_2015-09',
 'cash_debt_2015-10',
 'cash_debt_2015-11',
 'cash_debt_2015-12',
 'fcf_ocf_2010-01',
 'fcf_ocf_2010-02',
 'fcf_ocf_2010-03',
 'fcf_ocf_2010-04',
 'fcf_ocf_2010-05',
 'fcf_ocf_2010-06',
 'fcf_ocf_2010-07',
 'fcf_ocf_2010-08',
 'fcf_ocf_2010-09',
 'fcf_ocf_2010-10',
 'fcf_ocf_2010-11',
 'fcf_ocf_2010-12',
 'fcf_ocf_2011-01',
 'fcf_ocf_2011-02',
 'fcf_ocf_2011-03',
 'fcf_ocf_2011-04',
 'fcf_ocf_2011-05',
 'fcf_ocf_2011-06',
 'fcf_ocf_2011-07',
 'fcf_ocf_2011-08',
 'fcf_ocf_2011-09',
 'fcf_ocf_2011-10',
 'fcf_ocf_2011-11',
 'fcf_ocf_2011-12',
 'fcf_ocf_2012-01',
 'fcf_ocf_2012-02',
 'fcf_ocf_2012-03',
 'fcf_ocf_2012-04',
 'fcf_ocf_2012-05',
 'fcf_ocf_2012-06',
 'fcf_ocf_2012-07',
 'fcf_ocf_2012-08',
 'fcf_ocf_2012-09',
 'fcf_ocf_2012-10',
 'fcf_ocf_2012-11',
 'fcf_ocf_2012-12',
 'fcf_ocf_2013-01',
 'fcf_ocf_2013-02',
 'fcf_ocf_2013-03',
 'fcf_ocf_2013-04',
 'fcf_ocf_2013-05',
 'fcf_ocf_2013-06',
 'fcf_ocf_2013-07',
 'fcf_ocf_2013-08',
 'fcf_ocf_2013-09',
 'fcf_ocf_2013-10',
 'fcf_ocf_2013-11',
 'fcf_ocf_2013-12',
 'fcf_ocf_2014-01',
 'fcf_ocf_2014-02',
 'fcf_ocf_2014-03',
 'fcf_ocf_2014-04',
 'fcf_ocf_2014-05',
 'fcf_ocf_2014-06',
 'fcf_ocf_2014-07',
 'fcf_ocf_2014-08',
 'fcf_ocf_2014-09',
 'fcf_ocf_2014-10',
 'fcf_ocf_2014-11',
 'fcf_ocf_2014-12',
 'fcf_ocf_2015-01',
 'fcf_ocf_2015-02',
 'fcf_ocf_2015-03',
 ...]

In [7]:
trdt.head(10)

,PERMNO,price_20070103,price_20070104,price_20070105,price_20070108,price_20070109,price_20070110,price_20070111,price_20070112,price_20070116,...,at_turn_2015-03,at_turn_2015-04,at_turn_2015-05,at_turn_2015-06,at_turn_2015-07,at_turn_2015-08,at_turn_2015-09,at_turn_2015-10,at_turn_2015-11,at_turn_2015-12
0,10025,49.06,50.34,49.63,49.50,50.62,49.68,49.20,48.90,46.83,...,2.628,2.628,2.628,2.674,2.674,2.674,2.730,2.730,2.730,2.573
1,10026,41.02,41.89,39.66,40.42,40.54,41.54,41.41,42.23,41.71,...,1.340,1.340,1.348,1.348,1.348,1.357,1.357,1.357,1.349,1.349
2,10032,24.12,24.30,23.89,23.70,23.13,20.90,20.84,21.58,20.79,...,1.604,1.604,1.623,1.623,1.623,1.627,1.627,1.627,1.603,1.603
3,10051,7.40,7.33,7.52,7.44,7.51,7.52,7.45,7.60,7.83,...,0.786,0.786,0.787,0.787,0.787,0.822,0.822,0.822,0.834,0.834
4,10104,17.51,17.68,17.64,17.86,17.82,17.77,17.39,17.50,17.30,...,0.414,0.401,0.401,0.401,0.380,0.380,0.380,0.365,0.365,0.365
5,10107,29.86,29.81,29.64,29.93,29.96,29.66,30.70,31.21,31.16,...,0.553,0.553,0.544,0.544,0.544,0.537,0.537,0.537,0.518,0.518
6,10138,45.75,46.15,46.06,46.90,47.09,47.36,48.29,48.56,48.06,...,0.746,0.746,0.704,0.704,0.704,0.727,0.727,0.727,0.749,0.749
7,10145,45.10,45.08,44.65,44.92,45.24,44.96,45.71,45.56,45.62,...,0.887,0.887,0.868,0.868,0.868,0.858,0.858,0.858,0.846,0.846
8,10147,13.20,13.53,13.61,14.08,14.16,14.36,14.31,14.26,14.17,...,0.533,0.533,0.550,0.550,0.550,0.553,0.553,0.553,0.553,0.553
9,10158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.961,0.961,0.987,0.987,0.987,0.983,0.983,0.983,0.992,0.992

In [11]:
Permno.size

2060

In [8]:
X=pd.DataFrame(trdt).to_numpy()

In [9]:
X[47,2267:]

array([nan, nan, nan, ..., nan, nan, nan])

In [12]:
Permno=X[:,0]

In [13]:
perm=pd.DataFrame(data =Permno)
perm1=perm.rename(columns={0: 'PERMNO'})
perm1

       PERMNO
0     10025.0
1     10026.0
2     10032.0
3     10051.0
4     10104.0
...       ...
2055  93423.0
2056  93426.0
2057  93428.0
2058  93429.0
2059  93436.0

[2060 rows x 1 columns]

In [14]:
pricetr=X[:,1:2267]
indtr=X[:,2267:]

In [15]:
indtr.shape

(2060, 1368)

In [16]:
#transpose the dataset
tr1=np.transpose(pricetr)

tr2=np.transpose(indtr)

In [17]:
train1=pd.DataFrame(data =tr1)
train2=pd.DataFrame(data =tr2)

In [18]:
print("\nNumber of  stocks:", len(train1.columns))
print("\nNumber of days:", len(train1))

Number of  stocks: 2060

Number of days: 2266

In [19]:
train1.head()

,0,1,2,3,4,5,6,7,8,9,...,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059
0,49.06,41.02,24.12,7.40,17.51,29.86,45.75,45.10,13.20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50.34,41.89,24.30,7.33,17.68,29.81,46.15,45.08,13.53,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,49.63,39.66,23.89,7.52,17.64,29.64,46.06,44.65,13.61,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,49.50,40.42,23.70,7.44,17.86,29.93,46.90,44.92,14.08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,50.62,40.54,23.13,7.51,17.82,29.96,47.09,45.24,14.16,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
train2.head()

,0,1,2,3,4,5,6,7,8,9,...,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059
0,0.365,0.462,0.506,0.741,0.252,0.181,0.233,0.361,0.443,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.365,0.504,0.487,0.779,0.252,0.166,0.209,0.313,0.453,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.338,0.504,0.487,0.779,0.252,0.166,0.209,0.313,0.453,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.338,0.504,0.487,0.779,0.233,0.166,0.209,0.313,0.453,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.338,0.472,0.405,0.599,0.233,0.181,0.211,0.276,0.448,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
#Impute the datasets
train1.fillna(train1.mean(), inplace=True)
#train2.fillna(train2.mean(), inplace=True) #problem have rows with all nan, will deal with it separately

In [22]:
train1.head()

,0,1,2,3,4,5,6,7,8,9,...,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059
0,49.06,41.02,24.12,7.40,17.51,29.86,45.75,45.10,13.20,9.885732,...,19.818606,20.582484,7.538519,29.782328,29.003871,47.904683,15.039911,29.752606,40.833177,113.933877
1,50.34,41.89,24.30,7.33,17.68,29.81,46.15,45.08,13.53,9.885732,...,19.818606,20.582484,7.538519,29.782328,29.003871,47.904683,15.039911,29.752606,40.833177,113.933877
2,49.63,39.66,23.89,7.52,17.64,29.64,46.06,44.65,13.61,9.885732,...,19.818606,20.582484,7.538519,29.782328,29.003871,47.904683,15.039911,29.752606,40.833177,113.933877
3,49.50,40.42,23.70,7.44,17.86,29.93,46.90,44.92,14.08,9.885732,...,19.818606,20.582484,7.538519,29.782328,29.003871,47.904683,15.039911,29.752606,40.833177,113.933877
4,50.62,40.54,23.13,7.51,17.82,29.96,47.09,45.24,14.16,9.885732,...,19.818606,20.582484,7.538519,29.782328,29.003871,47.904683,15.039911,29.752606,40.833177,113.933877

In [23]:
train2.tail

<bound method NDFrame.tail of        0      1      2      3      4      5      6      7      8      9     \
0     0.365  0.462  0.506  0.741  0.252  0.181  0.233  0.361  0.443    NaN
1     0.365  0.504  0.487  0.779  0.252  0.166  0.209  0.313  0.453    NaN
2     0.338  0.504  0.487  0.779  0.252  0.166  0.209  0.313  0.453    NaN
3     0.338  0.504  0.487  0.779  0.233  0.166  0.209  0.313  0.453    NaN
4     0.338  0.472  0.405  0.599  0.233  0.181  0.211  0.276  0.448    NaN
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
1363  2.674  1.357  1.627  0.822  0.380  0.537  0.727  0.858  0.553  0.983
1364  2.730  1.357  1.627  0.822  0.380  0.537  0.727  0.858  0.553  0.983
1365  2.730  1.357  1.627  0.822  0.365  0.537  0.727  0.858  0.553  0.983
1366  2.730  1.349  1.603  0.834  0.365  0.518  0.749  0.846  0.553  0.992
1367  2.573  1.349  1.603  0.834  0.365  0.518  0.749  0.846  0.553  0.992

      ...   2050   2051   2052   2053   2054   2055   2056   2057   2058  \
0     ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
1     ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
2     ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
3     ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
4     ...    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN
...   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
1363  ...  1.608  0.438  0.691  0.187  0.301  0.458  0.847  0.529  1.631
1364  ...  1.608  0.395  0.691  0.187  0.301  0.458  0.847  0.529  1.631
1365  ...  1.608  0.395  0.691  0.187  0.301  0.458  0.847  0.529  1.631
1366  ...  1.581  0.395  0.742  0.155  0.271  0.472  0.847  0.521  1.698
1367  ...  1.581  0.388  0.742  0.155  0.271  0.472  0.847  0.521  1.698

       2059
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
...     ...
1363  0.620
1364  0.620
1365  0.620
1366  0.583
1367  0.583

[1368 rows x 2060 columns]>

In [25]:
#Transpsose again
imtr1=train1.T
imtr2=train2.T

In [47]:
imtr1.to_csv('imputedtrain1.csv')

In [67]:
#imtr2.to_csv('imputedtrain2.csv')

In [26]:
from sklearn.preprocessing import StandardScaler
x1 = StandardScaler().fit_transform(imtr1)
x2 =  StandardScaler().fit_transform(imtr2)

In [27]:
x2[47,:]

array([nan, nan, nan, ..., nan, nan, nan])

In [94]:
(np.isnan(x2)).any()

True

In [95]:
np.argwhere(np.isnan(x2))

array([[  47,    0],
       [  47,    1],
       [  47,    2],
       ...,
       [2002, 1365],
       [2002, 1366],
       [2002, 1367]])

In [28]:
k=15

In [81]:
k

15

In [29]:
from sklearn.decomposition import PCA
pca = PCA(n_components=k)
principalComponents1 = pca.fit_transform(x1)

In [30]:
Red1 = pd.DataFrame(data = principalComponents1
             , columns = range(1,k+1))

In [31]:
type(Red1)

pandas.core.frame.DataFrame

In [32]:
Red1.head(12)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,2.660520,2.943234,0.090046,-1.894355,5.060483,6.981604,3.945201,3.734542,-0.276868,1.422848,0.063031,2.932516,1.326073,-1.871520,0.153259
1,20.929629,10.413003,-3.344149,6.045255,0.540976,2.694806,1.459398,-1.228156,0.965623,0.791613,-0.136641,0.480383,-0.124342,-0.387489,-0.293851
2,-6.393924,1.332993,2.746831,2.774044,-1.996780,-1.663309,0.074506,1.714567,0.236020,1.796485,0.674637,-0.401746,-1.121315,1.102452,0.071496
3,-16.796843,4.370821,4.198720,2.511052,1.794202,-0.668591,1.052303,-0.942642,-0.853217,-0.581849,0.243187,-0.459938,0.085672,-0.150270,0.916831
4,-7.988193,3.467485,2.660182,2.926140,-0.925021,-0.537990,-0.509021,-0.302044,0.209060,0.445765,-0.318472,0.356342,0.595305,-0.577343,0.236504
5,-5.186191,-0.260557,-0.690565,1.957905,-0.162047,0.390312,-0.681610,1.090433,0.796172,1.349957,0.195855,-0.575791,-0.955133,-0.099651,-0.114998
6,25.911351,-0.943541,3.252015,0.638148,-0.360859,-2.152514,-0.030206,1.887221,-1.339725,0.561290,-0.605146,0.116826,0.221639,-0.437807,0.218522
7,25.530868,3.790936,-3.525778,-1.493869,1.075759,-2.476955,-1.074509,1.295786,0.227521,-0.690718,0.426071,0.168987,1.016485,-0.500913,-0.676826
8,-15.503851,3.088464,3.317643,0.673269,-1.097601,-0.094587,-0.730571,-0.070618,0.813732,0.951500,0.077168,0.118997,0.537312,-0.506164,-0.091880
9,-26.887160,0.366556,3.015344,2.017800,-0.292609,0.289536,-0.558734,-0.581357,0.732116,-0.062321,-0.048807,-0.086184,0.173956,0.102040,0.157293
10,-26.560303,9.683084,-4.333199,-0.116285,0.513347,-0.400748,-1.777834,0.203514,0.149195,1.127114,1.047434,0.327308,0.256815,0.346838,0.219210
11,9.670910,2.001549,3.655704,1.272686,-3.217738,0.665021,-0.303741,1.565494,1.126763,2.301349,-1.862495,0.504008,-1.068312,0.070018,-0.603528

In [99]:
Red1.to_csv('Reducedtrain1.csv')