In [1]:
import pandas as pd
import numpy as np
import os
import datetime

In [6]:
#import training dataset
trdt = pd.read_csv("training_data.csv")
print("\nNumber of stocks (rows):", len(trdt))
print("\nNumber of days (columns):", len(trdt.columns))

Number of stocks (rows): 2060

Number of days (columns): 3635

In [9]:
trdt.head(10)

,PERMNO,price_20070103,price_20070104,price_20070105,price_20070108,price_20070109,price_20070110,price_20070111,price_20070112,price_20070116,...,at_turn_2015-03,at_turn_2015-04,at_turn_2015-05,at_turn_2015-06,at_turn_2015-07,at_turn_2015-08,at_turn_2015-09,at_turn_2015-10,at_turn_2015-11,at_turn_2015-12
0,10025,49.06,50.34,49.63,49.50,50.62,49.68,49.20,48.90,46.83,...,2.628,2.628,2.628,2.674,2.674,2.674,2.730,2.730,2.730,2.573
1,10026,41.02,41.89,39.66,40.42,40.54,41.54,41.41,42.23,41.71,...,1.340,1.340,1.348,1.348,1.348,1.357,1.357,1.357,1.349,1.349
2,10032,24.12,24.30,23.89,23.70,23.13,20.90,20.84,21.58,20.79,...,1.604,1.604,1.623,1.623,1.623,1.627,1.627,1.627,1.603,1.603
3,10051,7.40,7.33,7.52,7.44,7.51,7.52,7.45,7.60,7.83,...,0.786,0.786,0.787,0.787,0.787,0.822,0.822,0.822,0.834,0.834
4,10104,17.51,17.68,17.64,17.86,17.82,17.77,17.39,17.50,17.30,...,0.414,0.401,0.401,0.401,0.380,0.380,0.380,0.365,0.365,0.365
5,10107,29.86,29.81,29.64,29.93,29.96,29.66,30.70,31.21,31.16,...,0.553,0.553,0.544,0.544,0.544,0.537,0.537,0.537,0.518,0.518
6,10138,45.75,46.15,46.06,46.90,47.09,47.36,48.29,48.56,48.06,...,0.746,0.746,0.704,0.704,0.704,0.727,0.727,0.727,0.749,0.749
7,10145,45.10,45.08,44.65,44.92,45.24,44.96,45.71,45.56,45.62,...,0.887,0.887,0.868,0.868,0.868,0.858,0.858,0.858,0.846,0.846
8,10147,13.20,13.53,13.61,14.08,14.16,14.36,14.31,14.26,14.17,...,0.533,0.533,0.550,0.550,0.550,0.553,0.553,0.553,0.553,0.553
9,10158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.961,0.961,0.987,0.987,0.987,0.983,0.983,0.983,0.992,0.992

In [7]:
#transpose the dataset
train=trdt.T
print("\nNumber of days:", len(train.columns))
print("\nNumber of stocks:", len(train))

Number of days: 2060

Number of stocks: 3635

In [10]:
train.head()

,0,1,2,3,4,5,6,7,8,9,...,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059
PERMNO,10025.00,10026.00,10032.00,10051.00,10104.00,10107.00,10138.00,10145.00,10147.00,10158.0,...,93384.0,93397.0,93401.0,93420.0,93422.0,93423.0,93426.0,93428.0,93429.0,93436.0
price_20070103,49.06,41.02,24.12,7.40,17.51,29.86,45.75,45.10,13.20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price_20070104,50.34,41.89,24.30,7.33,17.68,29.81,46.15,45.08,13.53,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price_20070105,49.63,39.66,23.89,7.52,17.64,29.64,46.06,44.65,13.61,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price_20070108,49.50,40.42,23.70,7.44,17.86,29.93,46.90,44.92,14.08,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
train.fillna(train.mean(), inplace=True)

In [12]:
train.head()

,0,1,2,3,4,5,6,7,8,9,...,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059
PERMNO,10025.00,10026.00,10032.00,10051.00,10104.00,10107.00,10138.00,10145.00,10147.00,10158.000000,...,93384.000000,93397.000000,93401.000000,93420.000000,93422.000000,93423.000000,93426.000000,93428.000000,93429.000000,93436.000000
price_20070103,49.06,41.02,24.12,7.40,17.51,29.86,45.75,45.10,13.20,10.381634,...,50.584819,47.114585,40.579277,51.721507,51.683426,62.221116,46.080519,51.716928,79.307587,95.701901
price_20070104,50.34,41.89,24.30,7.33,17.68,29.81,46.15,45.08,13.53,10.381634,...,50.584819,47.114585,40.579277,51.721507,51.683426,62.221116,46.080519,51.716928,79.307587,95.701901
price_20070105,49.63,39.66,23.89,7.52,17.64,29.64,46.06,44.65,13.61,10.381634,...,50.584819,47.114585,40.579277,51.721507,51.683426,62.221116,46.080519,51.716928,79.307587,95.701901
price_20070108,49.50,40.42,23.70,7.44,17.86,29.93,46.90,44.92,14.08,10.381634,...,50.584819,47.114585,40.579277,51.721507,51.683426,62.221116,46.080519,51.716928,79.307587,95.701901

In [45]:
train.to_csv('imputedtrainT.csv')

In [15]:
#Transpsose again
imtr=train.T

In [44]:
imtr.to_csv('imputedtrain.csv')

In [16]:
imtr.head(12)

,PERMNO,price_20070103,price_20070104,price_20070105,price_20070108,price_20070109,price_20070110,price_20070111,price_20070112,price_20070116,...,at_turn_2015-03,at_turn_2015-04,at_turn_2015-05,at_turn_2015-06,at_turn_2015-07,at_turn_2015-08,at_turn_2015-09,at_turn_2015-10,at_turn_2015-11,at_turn_2015-12
0,10025.0,49.060000,50.340000,49.630000,49.500000,50.620000,49.680000,49.200000,48.900000,46.830000,...,2.628,2.628,2.628,2.674,2.674,2.674,2.730,2.730,2.730,2.573
1,10026.0,41.020000,41.890000,39.660000,40.420000,40.540000,41.540000,41.410000,42.230000,41.710000,...,1.340,1.340,1.348,1.348,1.348,1.357,1.357,1.357,1.349,1.349
2,10032.0,24.120000,24.300000,23.890000,23.700000,23.130000,20.900000,20.840000,21.580000,20.790000,...,1.604,1.604,1.623,1.623,1.623,1.627,1.627,1.627,1.603,1.603
3,10051.0,7.400000,7.330000,7.520000,7.440000,7.510000,7.520000,7.450000,7.600000,7.830000,...,0.786,0.786,0.787,0.787,0.787,0.822,0.822,0.822,0.834,0.834
4,10104.0,17.510000,17.680000,17.640000,17.860000,17.820000,17.770000,17.390000,17.500000,17.300000,...,0.414,0.401,0.401,0.401,0.380,0.380,0.380,0.365,0.365,0.365
5,10107.0,29.860000,29.810000,29.640000,29.930000,29.960000,29.660000,30.700000,31.210000,31.160000,...,0.553,0.553,0.544,0.544,0.544,0.537,0.537,0.537,0.518,0.518
6,10138.0,45.750000,46.150000,46.060000,46.900000,47.090000,47.360000,48.290000,48.560000,48.060000,...,0.746,0.746,0.704,0.704,0.704,0.727,0.727,0.727,0.749,0.749
7,10145.0,45.100000,45.080000,44.650000,44.920000,45.240000,44.960000,45.710000,45.560000,45.620000,...,0.887,0.887,0.868,0.868,0.868,0.858,0.858,0.858,0.846,0.846
8,10147.0,13.200000,13.530000,13.610000,14.080000,14.160000,14.360000,14.310000,14.260000,14.170000,...,0.533,0.533,0.550,0.550,0.550,0.553,0.553,0.553,0.553,0.553
9,10158.0,10.381634,10.381634,10.381634,10.381634,10.381634,10.381634,10.381634,10.381634,10.381634,...,0.961,0.961,0.987,0.987,0.987,0.983,0.983,0.983,0.992,0.992
10,10180.0,5.890000,5.600000,5.560000,5.600000,5.940000,5.950000,5.950000,6.000000,6.020000,...,0.507,0.507,0.397,0.397,0.397,0.400,0.400,0.400,0.453,0.453
11,10182.0,38.040000,38.320000,37.760000,37.970000,38.210000,38.170000,38.050000,37.960000,37.780000,...,4.159,4.159,4.159,4.230,4.230,4.230,4.276,4.276,4.276,4.274

In [18]:
from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(imtr)

In [19]:
type(x)

numpy.ndarray

In [20]:
x[0][0:10]

array([-2.13369025,  0.31168446,  0.34280627,  0.33432249,  0.33023521,
        0.35717566,  0.32751126,  0.30437271,  0.28887314,  0.23519578])

In [36]:
k=20

In [37]:
from sklearn.decomposition import PCA
pca = PCA(n_components=k)
principalComponents = pca.fit_transform(x)

In [38]:
Red = pd.DataFrame(data = principalComponents
             , columns = range(1,k+1))

In [39]:
type(Red)

pandas.core.frame.DataFrame

In [40]:
Red.head(12)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,-0.368007,-10.064990,3.258395,-2.064776,-0.122476,0.437417,-1.691441,-0.378952,4.685162,1.747853,0.767909,-1.986625,4.625380,1.565074,-6.005434,-0.228474,-1.394960,1.943690,3.402267,-0.811967
1,17.263404,-15.265948,10.377799,-0.592472,-1.264367,3.611386,5.703059,-0.372988,-0.348697,0.175141,-0.546627,-0.829679,2.375297,1.716167,-2.684364,0.610822,-1.368347,0.980456,-0.663492,0.171209
2,-9.257404,-8.886697,1.729462,-3.045100,0.280410,-2.013369,2.178735,-0.865311,-2.539560,-0.975259,-0.157535,-0.259474,-1.356678,0.084584,-0.189043,0.061439,-0.320620,1.410063,0.685824,0.443304
3,-19.297072,-6.340624,4.602733,-2.218209,0.543421,-3.878398,2.416317,-0.923281,1.238673,0.577583,-0.303418,0.020604,-0.634216,-2.429120,-0.883158,-0.131245,0.631868,-1.032235,-0.026361,0.797480
4,-10.685237,-8.160566,3.739268,-2.239043,0.135653,-2.134893,2.601398,-0.535702,-1.333402,-0.242397,-0.349147,-0.102956,-0.325314,0.402752,0.395836,0.098520,-0.638689,0.208409,-0.475235,0.205712
5,-8.020903,-8.653002,0.005172,-1.563774,-0.549772,1.038135,1.699081,-0.186239,-0.790247,-0.105996,-0.431871,-0.103653,0.316800,0.256371,-0.584993,0.158502,-1.284655,0.648504,0.031124,0.177240
6,25.420029,-8.941868,-2.207598,10.907168,-0.051934,-8.921308,-1.016756,-0.355337,-0.331090,0.685508,-0.062857,-0.113599,-3.387376,-0.606147,2.222295,-0.029856,1.632075,0.420892,0.421859,-0.071026
7,21.675577,-15.951976,4.007436,-3.195450,-1.019994,5.279898,-0.985322,-1.130452,0.696493,0.657518,0.164144,-0.143853,-1.640525,-0.393431,1.103127,-0.491448,-0.691819,1.052132,0.277781,0.048707
8,-18.030978,-6.541919,3.459708,-2.620671,0.323330,-2.619319,0.525366,-0.332925,-0.932462,-0.573807,-0.174627,-0.289288,-0.026667,0.907121,0.848185,-0.002182,-0.886836,0.000512,-0.198669,-0.107960
9,-28.664099,-3.491453,0.243101,-1.646923,-0.002599,-2.793716,2.786971,-0.527510,1.252964,-1.531577,-0.923889,-1.872678,0.215772,3.276052,2.851294,0.487142,-1.082119,0.943428,-0.919849,0.476129
10,-28.555010,-3.558559,9.799527,2.092125,-1.507783,3.573766,-0.033424,-0.361130,0.131201,1.607344,-0.221949,-0.556576,-0.620588,3.631488,2.453295,0.374189,-1.326499,1.956474,-0.625882,-0.747754
11,6.366148,-12.164386,2.426045,-4.537645,0.557211,-2.196168,0.799011,-0.726372,-2.539257,-2.463383,0.000292,-0.275227,0.554876,0.083517,-0.929542,0.041225,-1.698855,0.633082,0.504913,-0.357297

In [41]:
len(Red)

2060

In [42]:
len(Red.columns)

20

In [43]:
Red.to_csv('Reducedtrain.csv')